name: MSMetaEnhancer-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >=3.7,<3.9
  - matchms >=0.9.2
  - pandas
  - scipy
  - requests
  - aiohttp
  - asyncstdlib
  - frozendict
  - tabulate
  - mock
  - pytest
  - pytest-aiohttp
  - pytest-cov
  - pytest-dependency
  - rdkit
  - multidict
