{% set name = "pyMSPannotator" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - bioconda

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  build:
    - conda-build
    - conda-verify
    - pytest-runner
    - python
    - setuptools
  host:
    - python >=3.7,<3.9
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >=3.7,<3.9
    - matchms >=0.9.1
    - pandas
    - scipy
    - requests
    - aiohttp
    - asyncstdlib
    - frozendict
    - tabulate
    - mock
    - pytest
    - pytest-aiohttp
    - pytest-cov

test:
  imports:
    - pyMSPannotator

about:
  home: https://github.com/RECETOX/pyMSPannotator
  license: MIT
  license_file: LICENSE
  summary: 'GC-MS retention index calculation'
  description: |
    Repository for tool that adds more annotations (e.g. SMILES, InChI, CAS number) to MSP files (Python version).
  dev_url: https://github.com/RECETOX/pyMSPannotator

extra:
  recipe-maintainers:
    - xtrojak
