{% set name = "MSMetaEnhancer" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . "

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matchms >=0.14.0
    - pandas
    - scipy
    - requests
    - aiohttp
    - asyncstdlib
    - frozendict
    - tabulate
    - rdkit
    - multidict

test:
  imports:
    - MSMetaEnhancer

about:
  home: https://github.com/RECETOX/MSMetaEnhancer
  license: MIT
  license_file: LICENSE
  summary: "MSMetaEnhancer is a python tool that adds more annotations (e.g. SMILES, InChI, CAS number) to MSP files."
  dev_url: "https://github.com/RECETOX/MSMetaEnhancer"

extra:
  recipe-maintainers:
    - xtrojak
    - hechth
